[versions]
agp = "9.0.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidXActivity = "1.12.4"
coil = "3.3.0"
compose = "1.10.1"
material3 = "1.10.0-alpha05"
kotlin = "2.3.10"
ktor = "3.4.0"

[libraries]
androidX-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidXActivity" }
coilKt-coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coilKt-coil3-networkKtor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
jetBrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
jetBrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
jetBrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
jetBrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
ktor-clientAndroid = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-clientDarwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
jetBrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetBrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetBrains-kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
